---
- name: Check for existence of cluster in db.
  register: cluster_check
  shell: "sacctmgr -n list cluster | cut -f 4 -d ' '"
  become: yes
  become_user: root  

- name: Create the slurmdbd cluster
  command: "sacctmgr -i -n add cluster {{ __slurm_config_default.ClusterName }}"
  become: yes
  become_user: root
  when: cluster_check.stdout != "cluster"
  
- name: Create commercial qos
  command: "sacctmgr add qos commercial priority=100"
  become: yes
  become_user: root
  when: cluster_check.stdout != "cluster"
